export const LOAD_WORKS_START = "LOAD_WORKS_START";
export const LOAD_WORKS_SUCCESS = "LOAD_WORKS_SUCCESS";
export const LOAD_WORKS_ERROR = "LOAD_WORKS_ERROR";

export const LOAD_WORK_START = "LOAD_WORK_START";
export const LOAD_WORK_SUCCESS = "LOAD_WORK_SUCCESS";
export const LOAD_WORK_ERROR = "LOAD_WORK_ERROR";

export const ADD_WORK_START = "ADD_WORK_START";
export const ADD_WORK_SUCCESS = "ADD_WORK_SUCCESS";
export const ADD_WORK_ERROR = "ADD_WORK_ERROR";

export const UPDATE_WORK_START = "UPDATE_WORK_START";
export const UPDATE_WORK_SUCCESS = "UPDATE_WORK_SUCCESS";
export const UPDATE_WORK_ERROR = "UPDATE_WORK_ERROR";

export const DELETE_WORK_START = "DELETE_WORK_START";
export const DELETE_WORK_SUCCESS = "DELETE_WORK_SUCCESS";
export const DELETE_WORK_ERROR = "DELETE_WORK_ERROR";

